version: '3'

services:
  mongo:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: defaultmongodb:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data/db:/host-data  # Bind mount host directory to container directory

  express:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./app-backend:/app